# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gridapp',
            options={'ordering': ['-Oluşturulma_Tarihi'], 'verbose_name': 'Profil', 'verbose_name_plural': 'Profil'},
        ),
        migrations.AddField(
            model_name='gridapp',
            name='Ekleyen',
            field=models.CharField(default='', help_text='Ekleyen :', max_length=100),
        ),
        migrations.AddField(
            model_name='gridapp',
            name='Icerik',
            field=models.TextField(default='', help_text='Haber İçeriği :'),
        ),
        migrations.AddField(
            model_name='gridapp',
            name='Oluşturulma_Tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gridapp',
            name='Resim',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
