# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridapp', '0002_auto_20171210_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='turu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tur', models.CharField(help_text='Haberin türü :', max_length=100)),
                ('Oluşturulma_Tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tur',
                'verbose_name_plural': 'Tur',
            },
        ),
        migrations.CreateModel(
            name='yeri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Yer', models.CharField(help_text='Haberin yeri :', max_length=100)),
                ('Oluşturulma_Tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yer',
                'verbose_name_plural': 'Yer',
            },
        ),
    ]
