# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridapp', '0003_turu_yeri'),
    ]

    operations = [
        migrations.DeleteModel(
            name='turu',
        ),
        migrations.DeleteModel(
            name='yeri',
        ),
        migrations.AddField(
            model_name='gridapp',
            name='Alt_baslik',
            field=models.CharField(default='', help_text='Alt Başlık :', max_length=100),
        ),
        migrations.AlterField(
            model_name='gridapp',
            name='Ekleyen',
            field=models.CharField(help_text='Ekleyen :', max_length=100),
        ),
        migrations.AlterField(
            model_name='gridapp',
            name='Icerik',
            field=models.TextField(help_text='Haber İçeriği :'),
        ),
    ]
