# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridapp', '0004_auto_20171210_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridapp',
            name='Alt_baslik',
            field=models.CharField(help_text='Alt Başlık :', max_length=100),
        ),
    ]
