# Generated by Django 2.0.7 on 2020-08-14 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gridapp', '0005_auto_20171210_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='altbaslik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='baslik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ekleyen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='gridapp',
            name='Alt_baslik',
            field=models.ForeignKey(help_text='Alt Başlık :', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='gridapp.altbaslik'),
        ),
        migrations.AlterField(
            model_name='gridapp',
            name='Baslik',
            field=models.ForeignKey(help_text='Başlık :', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='gridapp.baslik'),
        ),
        migrations.AlterField(
            model_name='gridapp',
            name='Ekleyen',
            field=models.ForeignKey(help_text='Ekleyen :', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='gridapp.ekleyen'),
        ),
    ]
